//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen dispensasjonssoeknad.xsd -c -o GeneratedClasses --sf
namespace No.Dibk.Ft.Skjema.Dispensasjonssoeknad.V1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("BegrunnelseType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class BegrunnelseType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("hensynBakBestemmelsen", IsNullable=true)]
        public string HensynBakBestemmelsen { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("vurderingHensynBakBestemmelsen", IsNullable=true)]
        public string VurderingHensynBakBestemmelsen { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("vurderingHensynOverordnet", IsNullable=true)]
        public string VurderingHensynOverordnet { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _fordeler;
        
        [System.Xml.Serialization.XmlArrayAttribute("fordeler", IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("effekt", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
        public System.Collections.ObjectModel.Collection<string> Fordeler
        {
            get
            {
                return _fordeler;
            }
            private set
            {
                _fordeler = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Fordeler collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FordelerSpecified
        {
            get
            {
                return (this.Fordeler.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="BegrunnelseType" /> class.</para>
        /// </summary>
        public BegrunnelseType()
        {
            this._fordeler = new System.Collections.ObjectModel.Collection<string>();
            this._ulemper = new System.Collections.ObjectModel.Collection<string>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _ulemper;
        
        [System.Xml.Serialization.XmlArrayAttribute("ulemper", IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("effekt", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
        public System.Collections.ObjectModel.Collection<string> Ulemper
        {
            get
            {
                return _ulemper;
            }
            private set
            {
                _ulemper = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Ulemper collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UlemperSpecified
        {
            get
            {
                return (this.Ulemper.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("samletBegrunnelse", IsNullable=true)]
        public string SamletBegrunnelse { get; set; }
    }
}
