//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen dispensasjonssoeknad.xsd -c -o GeneratedClasses --sf
namespace No.Dibk.Ft.Skjema.Dispensasjonssoeknad.V1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("DispensasjonssoeknadType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    [System.Xml.Serialization.XmlRootAttribute("dispensasjonssoeknad", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class DispensasjonssoeknadType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("soeknadstype", IsNullable=true)]
        public KodeType Soeknadstype { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("dispensasjonReferanse", IsNullable=true)]
        public string DispensasjonReferanse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("tiltakstyper", IsNullable=true)]
        public TiltakstyperType Tiltakstyper { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("dispensasjonBeskrivelse")]
        public DispensasjonBeskrivelseType DispensasjonBeskrivelse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("dispensasjonFra", IsNullable=true)]
        public DispensasjonFraType DispensasjonFra { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("stedfesting", IsNullable=true)]
        public StedfestingType Stedfesting { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("varighet")]
        public VarighetType Varighet { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("begrunnelse", IsNullable=true)]
        public BegrunnelseType Begrunnelse { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _dataFormatProvider = "DIBK";
        
        [System.Xml.Serialization.XmlAttributeAttribute("dataFormatProvider")]
        public string DataFormatProvider
        {
            get
            {
                return _dataFormatProvider;
            }
            set
            {
                _dataFormatProvider = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _dataFormatId = "10007";
        
        [System.Xml.Serialization.XmlAttributeAttribute("dataFormatId")]
        public string DataFormatId
        {
            get
            {
                return _dataFormatId;
            }
            set
            {
                _dataFormatId = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _dataFormatVersion = "1";
        
        [System.Xml.Serialization.XmlAttributeAttribute("dataFormatVersion")]
        public string DataFormatVersion
        {
            get
            {
                return _dataFormatVersion;
            }
            set
            {
                _dataFormatVersion = value;
            }
        }
    }
}
