//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen dispensasjonssoeknad.xsd -c -o GeneratedClasses --sf
namespace No.Dibk.Ft.Skjema.Dispensasjonssoeknad.V1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("DispensasjonPlanBestemmelseType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class DispensasjonPlanBestemmelseType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("navn", IsNullable=true)]
        public string Navn { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("nasjonalArealplanId", IsNullable=true)]
        public NasjonalArealplanIdType NasjonalArealplanId { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("planbestemmelse", IsNullable=true)]
        public PlanbestemmelseType Planbestemmelse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("gradAvUtnytting", IsNullable=true)]
        public string GradAvUtnytting { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("beregningsregelGradAvUtnytting", IsNullable=true)]
        public KodeType BeregningsregelGradAvUtnytting { get; set; }
    }
}
