//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen dispensasjonssoeknad.xsd -c -o GeneratedClasses --sf
namespace No.Dibk.Ft.Skjema.Dispensasjonssoeknad.V1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("DispensasjonBeskrivelseType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class DispensasjonBeskrivelseType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("dispensasjonTittel", IsNullable=true)]
        public KodeType DispensasjonTittel { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("inngangsbeskrivelse", IsNullable=true)]
        public KodeType Inngangsbeskrivelse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("annenInngangsbeskrivelse", IsNullable=true)]
        public string AnnenInngangsbeskrivelse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("beskrivelse", IsNullable=true)]
        public string Beskrivelse { get; set; }
    }
}
