//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen dispensasjonssoeknad.xsd -c -o GeneratedClasses --sf
namespace No.Dibk.Ft.Skjema.Dispensasjonssoeknad.V1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("FordelerListe", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class FordelerListe
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _effekt;
        
        [System.Xml.Serialization.XmlElementAttribute("effekt")]
        public System.Collections.ObjectModel.Collection<string> Effekt
        {
            get
            {
                return _effekt;
            }
            private set
            {
                _effekt = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Effekt collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EffektSpecified
        {
            get
            {
                return (this.Effekt.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="FordelerListe" /> class.</para>
        /// </summary>
        public FordelerListe()
        {
            this._effekt = new System.Collections.ObjectModel.Collection<string>();
        }
    }
}
