//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen dispensasjonssoeknad.xsd -c -o GeneratedClasses --sf
namespace No.Dibk.Ft.Skjema.Dispensasjonssoeknad.V1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("KodeListe", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class KodeListe
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<KodeType> _kode;
        
        [System.Xml.Serialization.XmlElementAttribute("kode")]
        public System.Collections.ObjectModel.Collection<KodeType> Kode
        {
            get
            {
                return _kode;
            }
            private set
            {
                _kode = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Kode collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KodeSpecified
        {
            get
            {
                return (this.Kode.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="KodeListe" /> class.</para>
        /// </summary>
        public KodeListe()
        {
            this._kode = new System.Collections.ObjectModel.Collection<KodeType>();
        }
    }
}
