//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen dispensasjonssoeknad.xsd -c -o GeneratedClasses --sf
namespace No.Dibk.Ft.Skjema.Dispensasjonssoeknad.V1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("KodeType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class KodeType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("kodeverdi", IsNullable=true)]
        public string Kodeverdi { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("kodebeskrivelse", IsNullable=true)]
        public string Kodebeskrivelse { get; set; }
    }
}
