//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen dispensasjonssoeknad.xsd -c -o GeneratedClasses --sf
namespace No.Dibk.Ft.Skjema.Dispensasjonssoeknad.V1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("KoordinatType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class KoordinatType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<double> _koordinat;
        
        [System.Xml.Serialization.XmlElementAttribute("koordinat")]
        public System.Collections.ObjectModel.Collection<double> Koordinat
        {
            get
            {
                return _koordinat;
            }
            private set
            {
                _koordinat = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="KoordinatType" /> class.</para>
        /// </summary>
        public KoordinatType()
        {
            this._koordinat = new System.Collections.ObjectModel.Collection<double>();
        }
    }
}
