//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen dispensasjonssoeknad.xsd -c -o GeneratedClasses --sf
namespace No.Dibk.Ft.Skjema.Dispensasjonssoeknad.V1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("PosisjonType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class PosisjonType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("type", IsNullable=true)]
        public KodeType Type { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("koordinatsystem", IsNullable=true)]
        public KodeType Koordinatsystem { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<double> _koordinater;
        
        [System.Xml.Serialization.XmlArrayAttribute("koordinater", IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("koordinat", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
        public System.Collections.ObjectModel.Collection<double> Koordinater
        {
            get
            {
                return _koordinater;
            }
            private set
            {
                _koordinater = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Koordinater collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KoordinaterSpecified
        {
            get
            {
                return (this.Koordinater.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PosisjonType" /> class.</para>
        /// </summary>
        public PosisjonType()
        {
            this._koordinater = new System.Collections.ObjectModel.Collection<double>();
        }
    }
}
