//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen dispensasjonssoeknad.xsd -c -o GeneratedClasses --sf
namespace No.Dibk.Ft.Skjema.Dispensasjonssoeknad.V1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("TiltakstyperType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class TiltakstyperType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<KodeType> _type;
        
        [System.Xml.Serialization.XmlArrayAttribute("type", IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("kode", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
        public System.Collections.ObjectModel.Collection<KodeType> Type
        {
            get
            {
                return _type;
            }
            private set
            {
                _type = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Type collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified
        {
            get
            {
                return (this.Type.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TiltakstyperType" /> class.</para>
        /// </summary>
        public TiltakstyperType()
        {
            this._type = new System.Collections.ObjectModel.Collection<KodeType>();
        }
    }
}
