//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen dispensasjonssoeknad.xsd -c -o GeneratedClasses --sf
namespace No.Dibk.Ft.Skjema.Dispensasjonssoeknad.V1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("VarighetType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class VarighetType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("oenskesVarigDispensasjon", IsNullable=true)]
        public System.Nullable<bool> OenskesVarigDispensasjon { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the OenskesVarigDispensasjon property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OenskesVarigDispensasjonSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("oensketVarighetTil", IsNullable=true, DataType="date")]
        public System.Nullable<System.DateTime> OensketVarighetTil { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the OensketVarighetTil property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OensketVarighetTilSpecified { get; set; }
    }
}
