//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen dispensasjonssoeknad.xsd -c -o GeneratedClasses
namespace No.Dibk.Ft.Skjema.Dispensasjonssoeknad.V1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("DispensasjonssoeknadType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    [System.Xml.Serialization.XmlRootAttribute("dispensasjonssoeknad", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class DispensasjonssoeknadType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("soeknadstype", IsNullable=true)]
        public KodeType Soeknadstype { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("dispensasjonReferanse", IsNullable=true)]
        public string DispensasjonReferanse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("tiltakstyper", IsNullable=true)]
        public TiltakstyperType Tiltakstyper { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("dispensasjonBeskrivelse")]
        public DispensasjonBeskrivelseType DispensasjonBeskrivelse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("dispensasjonFra", IsNullable=true)]
        public DispensasjonFraType DispensasjonFra { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("stedfesting", IsNullable=true)]
        public StedfestingType Stedfesting { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("varighet")]
        public VarighetType Varighet { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("begrunnelse", IsNullable=true)]
        public BegrunnelseType Begrunnelse { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _dataFormatProvider = "DIBK";
        
        [System.Xml.Serialization.XmlAttributeAttribute("dataFormatProvider")]
        public string DataFormatProvider
        {
            get
            {
                return _dataFormatProvider;
            }
            set
            {
                _dataFormatProvider = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _dataFormatId = "10007";
        
        [System.Xml.Serialization.XmlAttributeAttribute("dataFormatId")]
        public string DataFormatId
        {
            get
            {
                return _dataFormatId;
            }
            set
            {
                _dataFormatId = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _dataFormatVersion = "1";
        
        [System.Xml.Serialization.XmlAttributeAttribute("dataFormatVersion")]
        public string DataFormatVersion
        {
            get
            {
                return _dataFormatVersion;
            }
            set
            {
                _dataFormatVersion = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("KodeType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class KodeType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("kodeverdi", IsNullable=true)]
        public string Kodeverdi { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("kodebeskrivelse", IsNullable=true)]
        public string Kodebeskrivelse { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("TiltakstyperType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class TiltakstyperType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<KodeType> _type;
        
        [System.Xml.Serialization.XmlArrayAttribute("type", IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("kode", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
        public System.Collections.ObjectModel.Collection<KodeType> Type
        {
            get
            {
                return _type;
            }
            private set
            {
                _type = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Type collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified
        {
            get
            {
                return (this.Type.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TiltakstyperType" /> class.</para>
        /// </summary>
        public TiltakstyperType()
        {
            this._type = new System.Collections.ObjectModel.Collection<KodeType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("KodeListe", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class KodeListe
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<KodeType> _kode;
        
        [System.Xml.Serialization.XmlElementAttribute("kode")]
        public System.Collections.ObjectModel.Collection<KodeType> Kode
        {
            get
            {
                return _kode;
            }
            private set
            {
                _kode = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Kode collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KodeSpecified
        {
            get
            {
                return (this.Kode.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="KodeListe" /> class.</para>
        /// </summary>
        public KodeListe()
        {
            this._kode = new System.Collections.ObjectModel.Collection<KodeType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("DispensasjonBeskrivelseType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class DispensasjonBeskrivelseType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("dispensasjonTittel", IsNullable=true)]
        public KodeType DispensasjonTittel { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("inngangsbeskrivelse", IsNullable=true)]
        public KodeType Inngangsbeskrivelse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("annenInngangsbeskrivelse", IsNullable=true)]
        public string AnnenInngangsbeskrivelse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("beskrivelse", IsNullable=true)]
        public string Beskrivelse { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("DispensasjonFraType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class DispensasjonFraType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("bestemmelserType", IsNullable=true)]
        public KodeType BestemmelserType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("dispensasjonPlanBestemmelse", IsNullable=true)]
        public DispensasjonPlanBestemmelseType DispensasjonPlanBestemmelse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lovbestemmelse", IsNullable=true)]
        public string Lovbestemmelse { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("DispensasjonPlanBestemmelseType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class DispensasjonPlanBestemmelseType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("navn", IsNullable=true)]
        public string Navn { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("nasjonalArealplanId", IsNullable=true)]
        public NasjonalArealplanIdType NasjonalArealplanId { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("planbestemmelse", IsNullable=true)]
        public PlanbestemmelseType Planbestemmelse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("gradAvUtnytting", IsNullable=true)]
        public string GradAvUtnytting { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("beregningsregelGradAvUtnytting", IsNullable=true)]
        public KodeType BeregningsregelGradAvUtnytting { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("NasjonalArealplanIdType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class NasjonalArealplanIdType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("administrativEnhet", IsNullable=true)]
        public string AdministrativEnhet { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("planidentifikasjon", IsNullable=true)]
        public string Planidentifikasjon { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("PlanbestemmelseType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class PlanbestemmelseType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("nummerering", IsNullable=true)]
        public string Nummerering { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("overskrift", IsNullable=true)]
        public string Overskrift { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("bestemmelsestekst", IsNullable=true)]
        public string Bestemmelsestekst { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("StedfestingType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class StedfestingType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("posisjon", IsNullable=true)]
        public PosisjonType Posisjon { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("vertikalnivaa", IsNullable=true)]
        public KodeType Vertikalnivaa { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("PosisjonType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class PosisjonType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("type", IsNullable=true)]
        public KodeType Type { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("koordinatsystem", IsNullable=true)]
        public KodeType Koordinatsystem { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<double> _koordinater;
        
        [System.Xml.Serialization.XmlArrayAttribute("koordinater", IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("koordinat", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
        public System.Collections.ObjectModel.Collection<double> Koordinater
        {
            get
            {
                return _koordinater;
            }
            private set
            {
                _koordinater = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Koordinater collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KoordinaterSpecified
        {
            get
            {
                return (this.Koordinater.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PosisjonType" /> class.</para>
        /// </summary>
        public PosisjonType()
        {
            this._koordinater = new System.Collections.ObjectModel.Collection<double>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("KoordinatType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class KoordinatType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<double> _koordinat;
        
        [System.Xml.Serialization.XmlElementAttribute("koordinat")]
        public System.Collections.ObjectModel.Collection<double> Koordinat
        {
            get
            {
                return _koordinat;
            }
            private set
            {
                _koordinat = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="KoordinatType" /> class.</para>
        /// </summary>
        public KoordinatType()
        {
            this._koordinat = new System.Collections.ObjectModel.Collection<double>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("VarighetType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class VarighetType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("oenskesVarigDispensasjon", IsNullable=true)]
        public System.Nullable<bool> OenskesVarigDispensasjon { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the OenskesVarigDispensasjon property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OenskesVarigDispensasjonSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("oensketVarighetTil", IsNullable=true, DataType="date")]
        public System.Nullable<System.DateTime> OensketVarighetTil { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the OensketVarighetTil property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OensketVarighetTilSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("BegrunnelseType", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class BegrunnelseType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("hensynBakBestemmelsen", IsNullable=true)]
        public string HensynBakBestemmelsen { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("vurderingHensynBakBestemmelsen", IsNullable=true)]
        public string VurderingHensynBakBestemmelsen { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("vurderingHensynOverordnet", IsNullable=true)]
        public string VurderingHensynOverordnet { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _fordeler;
        
        [System.Xml.Serialization.XmlArrayAttribute("fordeler", IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("effekt", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
        public System.Collections.ObjectModel.Collection<string> Fordeler
        {
            get
            {
                return _fordeler;
            }
            private set
            {
                _fordeler = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Fordeler collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FordelerSpecified
        {
            get
            {
                return (this.Fordeler.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="BegrunnelseType" /> class.</para>
        /// </summary>
        public BegrunnelseType()
        {
            this._fordeler = new System.Collections.ObjectModel.Collection<string>();
            this._ulemper = new System.Collections.ObjectModel.Collection<string>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _ulemper;
        
        [System.Xml.Serialization.XmlArrayAttribute("ulemper", IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("effekt", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
        public System.Collections.ObjectModel.Collection<string> Ulemper
        {
            get
            {
                return _ulemper;
            }
            private set
            {
                _ulemper = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Ulemper collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UlemperSpecified
        {
            get
            {
                return (this.Ulemper.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("samletBegrunnelse", IsNullable=true)]
        public string SamletBegrunnelse { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("FordelerListe", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class FordelerListe
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _effekt;
        
        [System.Xml.Serialization.XmlElementAttribute("effekt")]
        public System.Collections.ObjectModel.Collection<string> Effekt
        {
            get
            {
                return _effekt;
            }
            private set
            {
                _effekt = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Effekt collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EffektSpecified
        {
            get
            {
                return (this.Effekt.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="FordelerListe" /> class.</para>
        /// </summary>
        public FordelerListe()
        {
            this._effekt = new System.Collections.ObjectModel.Collection<string>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.Xml.Serialization.XmlTypeAttribute("UlemperListe", Namespace="https://skjema.ft.dibk.no/dispensasjonssoeknad/v1")]
    public partial class UlemperListe
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _effekt;
        
        [System.Xml.Serialization.XmlElementAttribute("effekt")]
        public System.Collections.ObjectModel.Collection<string> Effekt
        {
            get
            {
                return _effekt;
            }
            private set
            {
                _effekt = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Effekt collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EffektSpecified
        {
            get
            {
                return (this.Effekt.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="UlemperListe" /> class.</para>
        /// </summary>
        public UlemperListe()
        {
            this._effekt = new System.Collections.ObjectModel.Collection<string>();
        }
    }
}
